const ITEMS = [
  {
    "id": "1",
    "saree_code": "CD_01",
    "thumbnail": "https://drive.google.com/thumbnail?id=11WxphbEuLINh4qnc8y_RBz9udhMSLLdc&sz=w2000",
    "images": ["https://drive.google.com/thumbnail?id=11WxphbEuLINh4qnc8y_RBz9udhMSLLdc&sz=w2000"],
    "name": "Cotton Printed Saree",
    "description": "Elegant cotton saree with traditional prints, perfect for daily and festive wear.",
    "rating": 4.9,
    "reviews_count": 220,
    "noOfOrders": 350,
    "price": 399.0,
    "discount_price": 300,
    "currency": "INR",
    "stock_status": "in_stock",
    "stock_count": 5,
    "category": "Sarees",
    "group": 1,
    "tags": ["cotton", "traditional", "casual"],
    "delivery_speed": "standard",
    "video": "https://www.youtube.com/watch?v=ysz5S6PUM-U"
  },
  {
    "id": "2",
    "saree_code": "CD_02",
    "thumbnail": "https://drive.google.com/thumbnail?id=1OW7aFw8LkRVUq9ukfzqQ8XBy2yZN8dMe&sz=w2000",
    "images": ["https://drive.google.com/thumbnail?id=1OW7aFw8LkRVUq9ukfzqQ8XBy2yZN8dMe&sz=w2000"],
    "name": "Silk Banarasi Saree",
    "description": "Luxurious Banarasi silk saree with golden zari work, ideal for weddings.",
    "rating": 4.8,
    "reviews_count": 180,
    "noOfOrders": 210,
    "price": 2499.0,
    "discount_price": 2249.1,
    "currency": "INR",
    "stock_status": "low_stock",
    "stock_count": 12,
    "category": "Sarees",
    "group": 2,
    "tags": ["silk", "banarasi", "wedding"],
    "delivery_speed": "express",
    "video": "https://www.youtube.com/watch?v=aqz-KE-bpKQ"
  },
  {
    "id": "3",
    "saree_code": "CD_03",
    "thumbnail": "https://drive.google.com/thumbnail?id=1-bnYk2X7_XCqmcTRYxXT4Jeqa8UT9xJV&sz=w2000",
    "images": ["https://drive.google.com/thumbnail?id=1-bnYk2X7_XCqmcTRYxXT4Jeqa8UT9xJV&sz=w2000"],
    "name": "Georgette Embroidered Saree",
    "description": "Lightweight georgette saree with delicate embroidery for party wear.",
    "rating": 4.6,
    "reviews_count": 145,
    "noOfOrders": 120,
    "price": 1399.0,
    "discount_price": 1259.1,
    "currency": "INR",
    "stock_status": "in_stock",
    "stock_count": 25,
    "category": "Sarees",
    "group": 3,
    "tags": ["georgette", "embroidery", "party"],
    "delivery_speed": "standard",
    "video": "https://www.youtube.com/watch?v=jNQXAC9IVRw"
  },
  {
    "id": "4",
    "saree_code": "CD_04",
    "thumbnail": "https://drive.google.com/thumbnail?id=1Hi-lLk8COsKu0omwl2EhHMrMMuTGcRnM&sz=w2000",
    "images": ["https://drive.google.com/thumbnail?id=1Hi-lLk8COsKu0omwl2EhHMrMMuTGcRnM&sz=w2000"],
    "name": "Linen Saree",
    "description": "Comfortable linen saree with pastel shades, perfect for summer.",
    "rating": 4.3,
    "reviews_count": 95,
    "noOfOrders": 75,
    "price": 999.0,
    "discount_price": 899.1,
    "currency": "INR",
    "stock_status": "in_stock",
    "stock_count": 40,
    "category": "Sarees",
    "group": 4,
    "tags": ["linen", "lightweight", "summer"],
    "delivery_speed": "standard",
    "video": "https://www.youtube.com/watch?v=5qap5aO4i9A"
  },
  {
    "id": "5",
    "saree_code": "CD_05",
    "thumbnail": "https://drive.google.com/thumbnail?id=1IKqi6hOin6WkfiBX2Qlb494MN6sNoLCH&sz=w2000",
    "images": ["https://drive.google.com/thumbnail?id=1IKqi6hOin6WkfiBX2Qlb494MN6sNoLCH&sz=w2000"],
    "name": "Kanchipuram Silk Saree",
    "description": "Pure Kanchipuram silk saree with intricate temple border design.",
    "rating": 4.9,
    "reviews_count": 310,
    "noOfOrders": 420,
    "price": 4999.0,
    "discount_price": 4499.1,
    "currency": "INR",
    "stock_status": "preorder",
    "stock_count": 0,
    "category": "Sarees",
    "group": 5,
    "tags": ["kanchipuram", "silk", "premium"],
    "delivery_speed": "express",
    "video": "https://www.youtube.com/watch?v=ScMzIvxBSi4"
  },
  {
    "id": "6",
    "saree_code": "CD_06",
    "thumbnail": "https://drive.google.com/thumbnail?id=1Y5kbZOSXzr-JS05pa9BPJ_V3-MBbOShg&sz=w2000",
    "images": ["https://drive.google.com/thumbnail?id=1Y5kbZOSXzr-JS05pa9BPJ_V3-MBbOShg&sz=w2000"],
    "name": "Chiffon Saree",
    "description": "Flowy chiffon saree with floral patterns, great for casual and office wear.",
    "rating": 4.1,
    "reviews_count": 80,
    "noOfOrders": 95,
    "price": 799.0,
    "discount_price": 719.1,
    "currency": "INR",
    "stock_status": "in_stock",
    "stock_count": 60,
    "category": "Sarees",
    "group": 6,
    "tags": ["chiffon", "light", "office"],
    "delivery_speed": "standard",
    "video": "https://www.youtube.com/watch?v=kXYiU_JCYtU"
  },
  {
    "id": "7",
    "saree_code": "CD_07",
    "thumbnail": "https://drive.google.com/thumbnail?id=1qyWtM8qpirXxoQmg2g5K5CpJNWYcmEci&sz=w2000",
    "images": ["https://drive.google.com/thumbnail?id=1qyWtM8qpirXxoQmg2g5K5CpJNWYcmEci&sz=w2000"],
    "name": "Cotton Handloom Saree",
    "description": "Handloom cotton saree crafted by skilled weavers, eco-friendly fabric.",
    "rating": 4.7,
    "reviews_count": 150,
    "noOfOrders": 180,
    "price": 1299.0,
    "discount_price": 1169.1,
    "currency": "INR",
    "stock_status": "in_stock",
    "stock_count": 35,
    "category": "Sarees",
    "group": 7,
    "tags": ["handloom", "eco", "cotton"],
    "delivery_speed": "standard",
    "video": "https://www.youtube.com/watch?v=ktvTqknDobU"
  }
];

export default ITEMS;
